version: '2'
services:

  #PHP Service
  pdf_table:
    build:
      context: .
      dockerfile: Dockerfile
    image: php-app
    restart: always
    tty: true
    environment:
      SERVICE_NAME: pdf_table
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
           - ./:/var/www
           - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini

  #Nginx Service
  nginx:
    image: nginx:alpine
    restart: always
    tty: true
    ports:
      - "8070:80"
      - "450:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d

